version: '3.7'

services:

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    container_name: es01
    environment:
      - cluster.name=es-docker-cluster
      - node.name=es01
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - xpack.security.enabled=true
      - xpack.security.transport.ssl.enabled=false
      - ELASTIC_PASSWORD=${ELASTIC_PASS}
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - ${VOLUME_DIR}/es01:/usr/share/elasticsearch/data
    networks:
      - elastic

  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    container_name: es02
    environment:
      - cluster.name=es-docker-cluster
      - node.name=es02
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - xpack.security.enabled=true
      - xpack.security.transport.ssl.enabled=false
      - ELASTIC_PASSWORD=${ELASTIC_PASS}
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - ${VOLUME_DIR}/es02:/usr/share/elasticsearch/data
    networks:
      - elastic

  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    container_name: es03
    environment:
      - cluster.name=es-docker-cluster
      - node.name=es03
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
      - xpack.security.enabled=true
      - xpack.security.transport.ssl.enabled=false
      - ELASTIC_PASSWORD=${ELASTIC_PASS}
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - ${VOLUME_DIR}/es03:/usr/share/elasticsearch/data
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:7.16.2
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - 'ELASTICSEARCH_HOSTS=["http://es01:9200", "http://es02:9200", "http://es03:9200"]'
      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASS}
      - ELASTICSEARCH_USERNAME=elastic
      - xpack.security.enabled=true
    networks:
      - elastic
    depends_on:
      - es01
      - es02
      - es03

  extractor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: extractor_job
    environment:
      - ELASTICSEARCH_USERNAME=mesdra
      - ELASTIC_PASSWORD=${ELASTIC_PASS}
      - ELASTICSEARCH_HOST=http://es01:9200
    depends_on:
      - es01
      - es02
      - es03
    networks:
      - elastic

networks:
  elastic:
    driver: bridge
